### ISSUE TITLE
Where to find the package called  `dca1000_device`?

### ISSUE THREAD

**Issue by nerdneilsfield** [Alphakyl/ijrr_ground_truth#1]
Hi,

I am trying to use the ROS format of the ColoRadar dataset to do some research. But I noticed many missing definitions of msgs, such as topic `/dca_node/heatmap,` which has the missing type `dca1000_device/MimoMsg`.  Will the definition of these messages be open-sourced in the future?

Your sincerely,

Neils

**Comment by Alphakyl** [comment]
My apologies we have not open sourced these message definitions but need to. Thank you for pointing this out. I will try to get you a link to a public repository as soon as possible.

**Comment by Alphakyl** [comment]
Hey @nerdneilsfield I have open-sourced the proper message definitions [here](https://github.com/arpg/dca1000_device_msgs). I'll also add a link to our website for future users.

**Comment by nerdneilsfield** [comment]
> Hey @nerdneilsfield I have open-sourced the proper message definitions [here](https://github.com/arpg/dca1000_device_msgs). I'll also add a link to our website for future users.

Good job! Thanks~
